### ISSUE TITLE
Cloglognormal issues with data at boundaries

### ISSUE THREAD

**Issue by Yannick73** [sims1253/bayesim#25]
The Cloglognormal BRMS may fail with input data too close to the boundaries.
Fixed by limiting data to [1e-12, 1 - 1e-12] in Stan-Code of cloglognormal_limited test function.

Is tested in three testcases:
- unchanged cloglognormal with input limited [1e-12, 1 - 1e-12] data, works
- new cloglognormal_limited with no limit in data, works
- unchanged cloglognormal with no limit in data, fails with error

Close by assessing the both BRMS implementations. Suggest using cloglognormal_limited, as it does not require any data manipulation by the user.
Fix found on Branch cloglog_brms_bugfix.

**Comment by sims1253** [comment]
That is a numeric weakness of the cloglog link and nothing we can really do about it than truncate inputs.
